
// 这个文件是生成的，请不要手动修改
import { FC, lazy, LazyExoticComponent, ComponentType } from 'react'; //

export type TC = LazyExoticComponent<ComponentType> | FC

export const routesData = {
    "/fubao/data-report/breast-cancer":lazy(() => import("../pages/fubao/data-report/breast-cancer/index")),
    "/fubao/data-report/cervical-cancer":lazy(() => import("../pages/fubao/data-report/cervical-cancer/index")),
    "/fubao/family-planning/booking-management":lazy(() => import("../pages/fubao/family-planning/booking-management/index")),
    "/fubao/family-planning/curettage-statistics":lazy(() => import("../pages/fubao/family-planning/curettage-statistics/index")),
    "/fubao/family-planning/file-management/doctor-desk":lazy(() => import("../pages/fubao/family-planning/file-management/doctor-desk/index")),
    "/fubao/family-planning/file-management/doctor-desk2":lazy(() => import("../pages/fubao/family-planning/file-management/doctor-desk2/index")),
    "/fubao/family-planning/file-management":lazy(() => import("../pages/fubao/family-planning/file-management/index")),
    "/fubao/family-planning/file-management/list":lazy(() => import("../pages/fubao/family-planning/file-management/list/index")),
    "/fubao/family-planning/file-management/nurse-desk":lazy(() => import("../pages/fubao/family-planning/file-management/nurse-desk/index")),
    "/fubao/family-planning/surgery-management":lazy(() => import("../pages/fubao/family-planning/surgery-management/index")),
    "/fubao/family-planning/surgery-scheduling":lazy(() => import("../pages/fubao/family-planning/surgery-scheduling/index")),
    "/fubao/family-planning/tracing-management":lazy(() => import("../pages/fubao/family-planning/tracing-management/index")),
    "/fubao/family-planning/tracing-management/list":lazy(() => import("../pages/fubao/family-planning/tracing-management/list/index")),
    "/fubao/folic-acid/file-management/add":lazy(() => import("../pages/fubao/folic-acid/file-management/add/index")),
    "/fubao/folic-acid/file-management/edit":lazy(() => import("../pages/fubao/folic-acid/file-management/edit/index")),
    "/fubao/folic-acid/file-management/list":lazy(() => import("../pages/fubao/folic-acid/file-management/list/index")),
    "/fubao/follow-up/positive/premarital":lazy(() => import("../pages/fubao/follow-up/positive/premarital/index")),
    "/fubao/follow-up/positive/progestation":lazy(() => import("../pages/fubao/follow-up/positive/progestation/index")),
    "/fubao/gynecological-diseases/adolescent-management/list":lazy(() => import("../pages/fubao/gynecological-diseases/adolescent-management/list/index")),
    "/fubao/gynecological-diseases/breast/edit":lazy(() => import("../pages/fubao/gynecological-diseases/breast/edit/index")),
    "/fubao/gynecological-diseases/breast/list":lazy(() => import("../pages/fubao/gynecological-diseases/breast/list/index")),
    "/fubao/gynecological-diseases/cervical/edit":lazy(() => import("../pages/fubao/gynecological-diseases/cervical/edit/index")),
    "/fubao/gynecological-diseases/cervical/list":lazy(() => import("../pages/fubao/gynecological-diseases/cervical/list/index")),
    "/fubao/gynecological-diseases/cervical-cancer-report/list":lazy(() => import("../pages/fubao/gynecological-diseases/cervical-cancer-report/list/index")),
    "/fubao/gynecological-diseases/hpv-report/list":lazy(() => import("../pages/fubao/gynecological-diseases/hpv-report/list/index")),
    "/fubao/gynecological-diseases/mammary-cancer-report/list":lazy(() => import("../pages/fubao/gynecological-diseases/mammary-cancer-report/list/index")),
    "/fubao/gynecological-diseases/menopause-management/list":lazy(() => import("../pages/fubao/gynecological-diseases/menopause-management/list/index")),
    "/fubao/gynecological-diseases/pathological-follow-up":lazy(() => import("../pages/fubao/gynecological-diseases/pathological-follow-up/index")),
    "/fubao/gynecological-diseases/pathological-reminder":lazy(() => import("../pages/fubao/gynecological-diseases/pathological-reminder/index")),
    "/fubao/gynecological-diseases/regular-screening/list":lazy(() => import("../pages/fubao/gynecological-diseases/regular-screening/list/index")),
    "/fubao/gynecological-diseases/two-cancers/add":lazy(() => import("../pages/fubao/gynecological-diseases/two-cancers/add/index")),
    "/fubao/gynecological-diseases/two-cancers/edit":lazy(() => import("../pages/fubao/gynecological-diseases/two-cancers/edit/index")),
    "/fubao/gynecological-diseases/two-cancers/exam":lazy(() => import("../pages/fubao/gynecological-diseases/two-cancers/exam/index")),
    "/fubao/gynecological-diseases/two-cancers/followup":lazy(() => import("../pages/fubao/gynecological-diseases/two-cancers/followup/index")),
    "/fubao/gynecological-diseases/two-cancers":lazy(() => import("../pages/fubao/gynecological-diseases/two-cancers/index")),
    "/fubao/pre-pregnancy-care/file-management/add":lazy(() => import("../pages/fubao/pre-pregnancy-care/file-management/add/index")),
    "/fubao/pre-pregnancy-care/file-management/edit":lazy(() => import("../pages/fubao/pre-pregnancy-care/file-management/edit/index")),
    "/fubao/pre-pregnancy-care/file-management":lazy(() => import("../pages/fubao/pre-pregnancy-care/file-management/index")),
    "/fubao/pre-pregnancy-care/husband/husband-exam":lazy(() => import("../pages/fubao/pre-pregnancy-care/husband/husband-exam/index")),
    "/fubao/pre-pregnancy-care/wife/wife-exam":lazy(() => import("../pages/fubao/pre-pregnancy-care/wife/wife-exam/index")),
    "/fubao/premarital-care/file-management/add":lazy(() => import("../pages/fubao/premarital-care/file-management/add/index")),
    "/fubao/premarital-care/file-management/edit":lazy(() => import("../pages/fubao/premarital-care/file-management/edit/index")),
    "/fubao/premarital-care/file-management":lazy(() => import("../pages/fubao/premarital-care/file-management/index")),
    "/fubao/premarital-care/husband-v2/husband-exam":lazy(() => import("../pages/fubao/premarital-care/husband-v2/husband-exam/index")),
    "/fubao/premarital-care/wife-v2/wife-exam":lazy(() => import("../pages/fubao/premarital-care/wife-v2/wife-exam/index")),
    "/fubao/report-entry/patients":lazy(() => import("../pages/fubao/report-entry/patients/index")),
    "/fubao/report-entry/reports":lazy(() => import("../pages/fubao/report-entry/reports/index")),
    "/fubao/statistic/abnormal-breast-cancer":lazy(() => import("../pages/fubao/statistic/abnormal-breast-cancer/index")),
    "/fubao/statistic/abnormal-cervical-cancer":lazy(() => import("../pages/fubao/statistic/abnormal-cervical-cancer/index")),
    "/fubao/statistic/breast-cancer":lazy(() => import("../pages/fubao/statistic/breast-cancer/index")),
    "/fubao/statistic/cervical-cancer":lazy(() => import("../pages/fubao/statistic/cervical-cancer/index")),
    "/fubao/statistic/premarital-checkup":lazy(() => import("../pages/fubao/statistic/premarital-checkup/index")),
    "/fubao/statistic/progestation-checkup":lazy(() => import("../pages/fubao/statistic/progestation-checkup/index")),
}