export type IMchc_FormDescriptions_InputType = "single_date_picker" |
    'PatientAutoComplete' |
    'rangeDate' |
    "MyButton" |
    "MyEditTable" |
    "MyRangeDate" |
    "MyRangeDateTime" |
    "MyInput" |
    "IdNOButton" |
    "Input" |
    "MySelect" |
    "MS" |
    "MyCheckbox" |
    "ArrayInput" |
    "search_select" |
    "TemplateTextarea" |
    "MyTemplateTextarea" |
    "MC" |
    "component" |
    "node" |
    "ArrayPanel" |
    "MyFormList_必须搭配Form使用" |
    "checkbox_group" |
    "MyPressure" |
    "title" |
    "normal_select" |
    "normal_checkbox_with_input" |
    "input" |
    "id" |
    "multiple_input_with_label" |
    "fetus_appendages" |
    "input_with_label" |
    "apgar_score_input" |
    "select_with_input" |
    "input_number" |
    "InputNumber" |
    "address" |
    "MyAddress" |
    "MyColor" |
    "MySwitch" |
    "radio" |
    "month_picker" |
    "single_time_picker" |
    "select_with_options" |
    "pregnant_radio" |
    "noenate_record" |
    "date" |
    "array-custom" |
    "table" |
    "checkbox" |
    "country_select" |
    "checkbox_with_input" |
    "text_area" |
    "MyMonaco" |
    "radio_group" |
    "checkbox_with_single_input" |
    "select_with_option" |
    "dictionary_select" |
    "id_number_input" |
    "input_with_range" |
    "pure_checkbox" |
    "checkbox_group_object" |
    "pregnancy_history_v2" |
    "has_pregnancy" |
    "fetal_count" |
    "custom" |
    "select" |
    "addressCascader" |
    "button" |
    "text-input" |
    "picker" |
    "date-picker" |
    "DatePicker" |
    "MyDatePicker" |
    "address-item" |
    "stepper-item" |
    "radio-item" |
    "checkbox-item" |
    "multiple-picker" |
    "group-picker" |
    "fetus" |
    "bloodPressureInput" |
    "MyAutoComplete" |
    "MA" |
    "MArr" |
    "textareaWithTemplate" |
    "blank" |
    "highrisk_sign" |
    "age_select" |
    "edit_in_table" |
    "diagnosis" |
    "template_textarea" |
    "input_with_range_tip" |
    "blood_pressure" |
    "blood_and_thalassemia" |
    "middle_ultsounds_single" |
    "select_with_options_or_input" |
    "fetal_nt_check" |
    "middle_ultsounds" |
    "procedure_records" |
    "surgical_before_operator_select" |
    "surgical_before_nurse_select" |
    "procedure_intrauterine_records" |
    "procedure_cystocentesis_records" |
    "pressure" |
    "select_tag_with_options" |
    "tree_select_v2" |
    "normalButton" |
    "textarea-input" |
    "referral_register" |
    "ToggleForm" |
    "referral_organization_select" |
    "record_state" |
    "patient_auto_complete" |
    "image_editor" |
    "post_partumFetal" |
    "calculate-score-table" |
    "inspection_report" |
    "nursing_fetus" |
    // "labor_processV2" |
    "HourMinuteInput" |
    "checkbox_with_inputv2" |
    "appgar" |
    "nurse_children" |
    "radio_input" |
    "pressure-v2" |
    "fetal_ultrasound" |
    "inspection_result_textarea" |
    "ultrosound_result_textarea" |
    "diagnosis_list" |
    "labor_process" |
    "label" |
    "textareaWithBtn" |
    "pregnancyHistoryTable" |
    "bregma_group" |
    "multiple_input_group" |
    "multi_selector" |
    "result_textarea" |
    "single_selector" |
    "check_invert_button" |
    "async_autoComplete" |
    "checkbox-with-extra" |
    "oxytocin_table" |
    "range_date_picker" |
    "caesarean_children" |
    "retained_fetus" |
    "template_textareav2" |
    "auto_complete_with_red" |
    "diagnosis_list_v2" |
    "normal_nursing_table" |
    // "pre_deliver_nursing_Table" |
    "blood_sugar_nursing_Table" |
    "past_delivery_nursing_table" |
    "special_nursing_table" |
    "oxytocin_nursing_table" |
    // "neonatal_care_table" |
    "lmp-info" |
    "induced_fetus" |
    "temperature_nursing_Table" |
    // "nursing_fetusv2" |
    // "post_partum_carerecord_Table2" |
    // "post_urinary_retention_Table" |
    // "obser_magnesium_sulphate_Table" |
    // "neonatal_scale_examination" |
    // "nursing_fetusv4" |
    // "rowoftire_record_baby" |
    "blank_part" |
    "vagina_struments_record_form" |
    "divider" |
    "template_textareav3" 
