import { formatDateTimeNoSecond } from '@lm_fe/utils';
import { APP_CONFIG } from '../../../utils/constants';
export const tableColumns_default = [
  {
    title: '日期',
    dataIndex: 'recordTime',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
    editable: true,
    align: 'center',
    inputType: 'DateTimeInput',
    inputProps: { showTime: true, format: formatDateTimeNoSecond.format },
    render: formatDateTimeNoSecond,
    sortType: 'date',
    filterType: 'date',
    showSorter: true,
    defaultSortOrder: 'descend',
    fixed: 'left',
  },
  {
    title: '体温(℃)',
    dataIndex: 'temperature',
    editable: true,
    align: 'center',
    inputType: 'input_number',
    inputProps: { min: 0 },
    width: APP_CONFIG.CELL_WIDTH_SMALL,
    render: (value: any) => value && (value >= 37.3 ? <div style={{ color: 'red' }}>{value}</div> : `${value}`),
  },
  {
    title: '哭声',
    dataIndex: 'weep',
    editable: true,
    align: 'center',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
    inputType: 'MyAutoComplete',
    inputProps: {
      uniqueKey: '哭声s',
    },
  },
  {
    title: '肤色',
    dataIndex: 'complexion',
    editable: true,
    align: 'center',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    title: '呼吸',
    dataIndex: 'breathing',
    editable: true,
    align: 'center',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    title: '反应',
    dataIndex: 'response',
    editable: true,
    align: 'center',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
    inputType: 'MyAutoComplete',
    inputProps: {
      uniqueKey: '反应s',
    },
  },
  {
    title: '呕吐',
    dataIndex: 'emesis',
    editable: true,
    align: 'center',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    title: '脐带',
    dataIndex: 'umbilicalcord',
    editable: true,
    align: 'center',
    inputType: 'MyAutoComplete',
    inputProps: {
      uniqueKey: '脐带s',
    },
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    title: '小便',
    dataIndex: 'pee',
    editable: true,
    align: 'center',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
    inputType: 'MyAutoComplete',
    inputProps: {
      uniqueKey: '小便s',
    },
  },
  {
    title: '其他',
    dataIndex: 'other',
    editable: true,
    align: 'center',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    title: '签名',
    dataIndex: 'recorder',
    align: 'center',
    width: APP_CONFIG.CELL_WIDTH_SMALL,
  },
];
