import { formatTimeToYearMonth } from '@/utils/format';
import { APP_CONFIG, MODAL_TEMPLATE_TYPES } from "@lm_fe/env";
export const tableColumns1 = [
  // {
  //   title: '日期',
  //   dataIndex: 'recordTime',
  //   width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  //   editable: true,
  //   align: 'center',
  //   inputType: 'single_date_picker',
  //   inputProps: { showTime: false, format: 'YYYY-MM-DD' },
  //   render: (value: any) => formatTimeToDate(value),
  //   sortType: 'date',
  //   filterType: 'date',
  //   showSorter: true,
  //   defaultInputData:true,
  //   defaultSortOrder: 'descend',
  //   fixed: 'left',
  // },

  {
    title: '时间',
    dataIndex: 'recordDateTime',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
    editable: true,
    align: 'center',
    inputType: 'DateTimeInput',
    inputProps: { showTime: true, format: 'YYYY-MM-DD HH:mm' },
    render: (value: any) => formatTimeToYearMonth(value),
    sortType: 'date',
    filterType: 'date',
    showSorter: true,
  },

  {
    title: '呼吸',
    dataIndex: 'breath',
    align: 'center',
    editable: true,
    inputType: 'MyInput',
    width: APP_CONFIG.CELL_WIDTH_SMALL,
  },
  {
    title: '膝反射',
    dataIndex: 'kneeJerk',
    align: 'center',
    editable: true,
    inputType: 'MyAutoComplete',
    inputProps: { uniqueKey: '膝反射s' },
    width: APP_CONFIG.CELL_WIDTH_SMALL,
  },
  {
    title: '尿量',
    align: 'center',
    dataIndex: 'urineVolume',
    editable: true,
    inputType: 'MyInput',
    width: APP_CONFIG.CELL_WIDTH_SMALL,
  },
  {
    title: '滴速g/h',
    dataIndex: 'speed',
    editable: true,
    align: 'center',
    inputType: 'MyInput',
    width: APP_CONFIG.CELL_WIDTH_SMALL,
  },
  {
    title: '护士签名',
    dataIndex: 'sign',
    editable: true,
    align: 'center',
    width: APP_CONFIG.CELL_WIDTH_SMALL,
    inputType: 'TextArea',
    inputProps: { type: MODAL_TEMPLATE_TYPES.科室个人, isPop: true, rows: 10 },
    fixed: 'right',
  },
];
