export const ACTION_TYPE = {
  USER_LOGIN: 'user.login',
  USER_LOGOUT: 'user.logout',
  INIT_USER: 'init.user',
  ADD_TAB: 'add.tabs',
  DELETE_TAB: 'delete.tabs',
  DELETE_ALL_TAB: 'delete.all.tabs',
  DELETE_OTHERS_TAB: 'delete.others.tabs',
  DELETE_RIGHT_TAB: 'delete.right.tabs',
  CHANGE_WOMEN_EXAM_RECORD_EDITING_ID: 'update.women.tempid',
  INIT_HIGH_RISK_WS: 'init_high_risk_ws',

  PRENATAL_VISIT_HEADERINFO: 'prenatal-visit.headerinfo',
  PRENATAL_VISIT_MAIN_DIAGNOSES: 'prenatal-visit.main.diagnoses',
  PRENATAL_VISIT_MAIN_DIAGNOSESTEMPLATE: 'prenatal-visit.main.diagnosesTemplate',
  PRENATAL_VISIT_MAIN_HIGHRISKDIAGNOSES: 'prenatal-visit.main.highriskDiagnoses',
  PRENATAL_VISIT_MAIN_HIGHRISKSIGN: 'prenatal-visit.main.highriskSign',
  PRENATAL_VISIT_MAIN_HIGHRISK: 'prenatal-visit.main.highrisk',
  PRENATAL_VISIT_MAIN_TOLAC: 'prenatal-visit.main.tolac',
  PRENATAL_VISIT_MAIN_PREECLAMPSIA: 'prenatal-visit.main.preeclampsia',
  PRENATAL_VISIT_MAIN_PREVENTPREECLAMPSIA: 'prenatal-visit.main.preventPreeclampsia',
  PRENATAL_VISIT_MAIN_SYPHILIS: 'prenatal-visit.main.syphilis',
  PRENATAL_VISIT_WEBSOCKET_INSTANCE: 'prenatal-visit.websocket.instance',
  PRENATAL_VISIT_WEBSOCKET: 'prenatal-visit.websocket',
  PRENATAL_VISIT_WEBSOCKET_SUM_CHANGE: 'prenatal-visit.websocket_sum_change',
  PRENATAL_VISIT_WEBSOCKET_DEL: 'prenatal-visit.websocket.del',
  PRENATAL_VISIT_WEBSOCKET_LEVEL_NEW: 'prenatal-visit.websocket.del.level.new',
  PRENATAL_VISIT_WEBSOCKET_CANCLEFORM: 'prenatal-visit.websocket.cancleform',
  PRENATAL_VISIT_WEBSOCKET_CHANGE_VISIBLE: 'prenatal-visit.websocket.change.visible',
  PRENATAL_VISIT_WEBSOCKET_CLOSE: 'prenatal-visit.websocket.close',
  PRENATAL_VISIT_WEBSOCKET_CLEAR: 'prenatal-visit.websocket.clear',
  PRENATAL_VISIT_WEBSOCKET_SHOW: 'prenatal-visit.websocket.show',
  PRENATAL_VISIT_WEBSOCKET_MULTITERM: 'prenatal-visit.websocket.multiterm',

  PRENATAL_DIAGNOSIS_CHANGE_PATIENT: 'prenatal-diagnosis.changePatient',
  PRENATAL_DIAGNOSIS_OPEN_SPIN: 'prenatal-diagnosis.openSpin',
  PRENATAL_DIAGNOSIS_CLOSE_SPIN: 'prenatal-diagnosis.closeSpin',
  GET_SYSTEM_CONFIG: 'system.config.get',
  UPDATE_SYSTEM_CONFIG: 'system.config.updated',
  UPDATE_SOCKET_STATE: 'system.socketState.updated',

  // pad 宣教
  UPDATE_ACTIVE_KEY: 'healthmission.update.activeKey',
  UPDATE_ARTICLE_TYPE: 'healthmission.update.articleType',
  UPDATE_VIDEO_TYPE: 'healthmission.update.videoType',
  UPDATE_ARTICLE_LIST: 'healthmission.update.articleList',
  UPDATE_VIDEO_LIST: 'healthmission.update.videoList',
};
